# Generated by Django 5.2.5 on 2025-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
