# Generated by Django 5.2.5 on 2025-09-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploading', max_length=20),
        ),
    ]
